### ISSUE TITLE
SSL cert for wollic.org has expired

### ISSUE THREAD

**Issue by m4lvin** [wollic2022/wollic2022.github.io#1]
Hi :wave:
Not sure if you can do something about it, but as the CfP from https://wollic2022.github.io/cfp.txt still mentions https://wollic.org/wollic2022 I wanted to let you know that the SSL certificate of wollic.org expired on 20 April.

**Comment by ciobaca** [comment]
Dear Malvin, thanks for letting us know. I'm informing the owner of wollic.org about the expired certificate.
